### PR TITLE
Update extend-android.md according to the latest Weex sdk

### PR DESCRIPTION
**Pull request by shikechen**
Original "Component" class and method are deprecated, so I want to improve this page according to the latest Weex sdk.

### CODE REVIEW

**Comment by shikechen** [comment]
Hi @Hanks10100 , I have modified the commit log in my repository but it doesn't work, so you can modify it to remove Chinese characters before merge.

**Comment by Hanks10100** [comment]
@shikechen You can try `git push -f` to force update your master branch. If I squash and modified your commits, your contribution info would be omitted. I'm not sure if you care about it.

**Comment by Hanks10100** [comment]
Not append commit logs, what I mean is to modify it... Never mind, I merged it anyway.

**Comment by shikechen** [comment]
@Hanks10100 OK. And when this page _https://weex.apache.org/cn/guide/extend-android.html_ updates according to the commits? Because now it‘s still original content.

**Pull request merged**
