### PR TITLE
[WEEX-86][doc] Adds a guide on how to create a plugin

### PR DESCRIPTION
**Pull request by tralves**
Greetings,

This PR adds the page "Create a plugin" to guide the user on the process of starting, developing, testing and deploying a plugin.

I hope it helps. Looking forward for your comments on it.

Thanks,
Tiago

### CODE REVIEW

**Comment by cxfeng1** [comment]
@Hanks10100 Please have a review.

**Comment by tralves** [comment]
This PR is outdated since yesterday, as Drew Hansen explained in [this email](https://mail-archives.apache.org/mod_mbox/incubator-weex-dev/201711.mbox/%3cCAHYLpMzROK6N4TG6Wcft6vh6CC=17Bvm+-=Fb77OCUitY_7jEg@mail.gmail.com%3e).

I will retest the process and update this PR accordingly.

**Comment by tralves** [comment]
@cxfeng1 @Hanks10100 @cthistle Updated the PR according to the latest developments in the plugin generator. It can be reviewed now.

Thanks

**Comment by Hanks10100** [comment]
I have already squash merged this PR into master, but its state doesn't change. Is there something wrong with my operation?

**Comment by Hanks10100** [comment]
Sorry for my misoperation, this PR is squash merged into master, but the apache bot doesn't update the state of this PR. I'll close this PR later. Sorry again.

**Pull request closed without merging**
